# Generated by Django 5.0.6 on 2024-07-09 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0002_customuser_is_private'),
    ]

    operations = [
        migrations.RenameField(
            model_name='following',
            old_name='following_user_id',
            new_name='following_user',
        ),
        migrations.RenameField(
            model_name='following',
            old_name='user_id',
            new_name='user',
        ),
    ]
