# Generated by Django 5.0.6 on 2024-07-10 08:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0004_messages'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='date_uploaded',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
